### ISSUE TITLE
MDX from /Widgets now includes filters

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/Cache-MDX2JSON#37]
New feature! Now (on tfoms) /Widget request returns MDX with all filters. 
Please, test it @ZitRos, @gnibeda

**Comment by ZitRos** [comment]
Jush make as it was before, without parsing filters.

**Comment by evshvarov** [comment]
Let's name it "noFilters"?. MHO it is better describes the option then
"basicMDX"

2015-01-04 18:46 GMT+03:00 Nikita <notifications@github.com>:

**Comment by ZitRos** [comment]
I agree, but if project reach a new MDX modification (parsing) in future, the meaning of "noFilters" name will be corrupted. Also I propose variants "cleanMDX", "originMDX" or much better "pivotMDX". What do you think?

**Comment by ZitRos** [comment]
> Let's name it "noFilters"?

I agree, but if project reach a new MDX modification (parsing) in future, the meaning of "noFilters" name will be corrupted. Also I propose variants "cleanMDX", "originMDX" or much better "pivotMDX". What do you think?

**Comment by adaptun** [comment]
I think it's bad to have parameter name start with negation like "no" or "not". You can always call this parameter IncludeFilters with default value true
