### ISSUE TITLE
Locale default formatting

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/Cache-MDX2JSON#42]
It is important for LPT to retrieve default number formatting based on locale settings. If this is possible, please, provide additional parameter like "defaultFormatting" of type "# ###,##" or replace emty "format" properties with such mask.

![2015-01-22_205922](https://cloud.githubusercontent.com/assets/4989256/5862325/982cfeb2-a279-11e4-841b-a6130e26a238.png)

**Comment by eduard93** [comment]
From where did you get this screenshot?

**Comment by eduard93** [comment]
Defaults are system-wide. 
Do you want a new separate method for access, or dump it into every MDX query? I'll probably do it as a separate method. No reason to do it every time.

**Comment by ZitRos** [comment]
Screenshot made from Administering > Config > Locale settings > Locale setup -> Properties.

So you are forcing LPT to make additional (third asynchronous) request to server each time widget loads, parse this data and replace empty formats with default. That is OK.

Probably the better way (easiest for user, but not for MDX2JSON developer :smile:) is to store parsed default formatting spec somewhere and replace empty formats on server by it in each response. This will just leave "tuples" structure "as it expected to be". But anyway, <code>/Format</code> is useful, thank you.

**Comment by eduard93** [comment]
@ZitRos the response is the same for every widget/pivot whatever. This values are system wide.

**Comment by eduard93** [comment]
![6e6ea5e3cd2cf14f60c9fa5cf3ce612f5fa50f929ad46723db pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/5127457/5877899/eef9334a-a333-11e4-99f0-d688ceb7b8a1.png)
