### ISSUE TITLE
Missed formatting spec for column

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/Cache-MDX2JSON#43]
[Demo page](http://37.139.4.54:57773/csp/tfoms/%25DeepSee.UserPortal.DashboardViewer.zen?DASHBOARD=TFOMS/AdmissionMOWaitingDashboardLP.dashboard&NOBORDER=1). Formatting on red-colored columns is wrong because there's no <i>filter</i> property specified for this column.

Info-graphic:
![2015-01-22_212139](https://cloud.githubusercontent.com/assets/4989256/5862798/542288be-a27d-11e4-8d55-0791ecf91cc3.png)

Possible related to #42.

**Comment by eduard93** [comment]
Probably it's formatted like this because of [Locale default formatting](https://github.com/intersystems-ru/Cache-MDX2JSON/issues/42) issue

**Comment by eduard93** [comment]
Seems to be it.
