### ISSUE TITLE
Incorrect formatting on different locales, default formatting

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/Cache-MDX2JSON#45]
NumericGroupSeparator was changed from "," to " ". Locale has been applied. Here is the responce from <code>/Format</code>:
```json
{
	"AM":"AM",
	"DateFormat":"YYYY-MM-DD",
	"DateSeparator":".",
	"DecimalSeparator":",",
	"MinusSign":"-",
	"MonthAbbr":" Янв Фев Мар Апр Май Июн Июл Авг Сен Окт Ноя Дек",
	"MonthName":" Январь Февраль Март Апрель Май Июнь Июль Август Сентябрь Октябрь Ноябрь Декабрь",
	"NumericGroupSeparator":" ",
	"NumericGroupSize":3,
	"PlusSign":"+",
	"PM":"PM",
	"TimeFormat":"hh:mm:ss",
	"TimePrecision":0,
	"TimeSeparator":":",
	"WeekdayAbbr":" Вос Пон Вто Сре Чет Пят Суб",
	"WeekdayName":" Воскресенье Понедельник Вторник Среда Четверг Пятница Суббота"
}
```

But the MDX2JSON still return incorrect formatting. Console shows the part of <code>/MDX</code> response:
![2015-01-23_204708](https://cloud.githubusercontent.com/assets/4989256/5880447/50701118-a341-11e4-948e-bffa664703eb.png)

I thought about making a demo on our server, but probably changing locale setting can be volatile so I left this idea. I think the problem is clear.

Also I suggest to parse any formatting mask (including default formatting) on the server side, just to avoid different conflicts. And applications should work in such way: <i>MDX2JSON gives formatting masks, app applies it</i>. LPT (or any other application) should not parse (generate) any masks, just apply them.

**Comment by eduard93** [comment]
Hmmm

**Comment by eduard93** [comment]
Formatting magic happens in class %DeepSee.Component.pivotTable method %DrawDataTable

**Comment by eduard93** [comment]
Testing @ZitRos

**Comment by ZitRos** [comment]
Still expect test results from Vladimir.

By the way, the default formatting is OK, but locale settings change still not affect set-up formatting rule "$#,###.##".

**Comment by eduard93** [comment]
"but locale settings change still not affect set-up formatting rule "$#,###.##"."
Please provide an example.

**Comment by eduard93** [comment]
http://37.139.4.54:57773/csp/tfoms/_DeepSee.UserPortal.DashboardViewer.zen?DASHBOARD=LPT/LPT%20plan%20test.dashboard&NOBORDER=1

**Comment by ZitRos** [comment]
Example on [tfoms](http://37.139.4.54:57773/csp/tfoms/_DeepSee.UserPortal.DashboardViewer.zen?DASHBOARD=LPT/LPT%20plan%20test.dashboard&NOBORDER=1).

MDX:
```SQL
SELECT NONEMPTYCROSSJOIN({[periodOnDateStart].[H1].[month].Members,%LABEL(,"Итого","",,"font-weight: bold;")},{%LABEL([Measures].[helpVolume],"","",,"background:rgb(208, 255, 208);"),%LABEL([Measures].[patientsHelpedCount],"","",,"background:rgb(208, 255, 208);"),%LABEL([Measures].[planHelpCost],"","",,"background:rgb(255, 208, 255);")}) ON 0,NON EMPTY [MUProfile].[H1].[MU].Members ON 1 FROM [PlanIndicatorCube] %FILTER [periodOnDateStart].[H1].[month].&[201402]
```

![2015-02-13_220420](https://cloud.githubusercontent.com/assets/4989256/6194364/60d1c2fe-b3cc-11e4-8408-fd1aff6e1fdd.png)
