### ISSUE TITLE
Latest installation fails to get widgets list

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/Cache-MDX2JSON#46]
![2015-05-24_165607](https://cloud.githubusercontent.com/assets/4989256/7788091/c858d004-0235-11e5-8b56-41ec8699e2ea.png)
I have just installed latest MDX2JSON (with automatic download from github option), and got this error when opened dashboards with configured LPT. Additionally, REST console return HTTP / 1.1 405 Method Not Allowed forever until I comment the line of code which returs error, then just returns nothing.

Could you please check it? Local check failed, and 37.139.4.54 is unreachable at the moment.

**Comment by eduard93** [comment]
Unable to replicate.
![default](https://cloud.githubusercontent.com/assets/5127457/7788165/bb6aef28-0238-11e5-89e4-6f9639b70149.PNG)

1. Can you please provide error message?
2. List the names of widgets' respective datasources

**Comment by ZitRos** [comment]
> Can you please provide error message?

ON http://localhost:57773/MDX2JSON/Widgets?Namespace=SAMPLES :  {"Error":"ОШИБКА #5659: Отсутствует свойство 'MDX'"}



> List the names of widgets' respective datasources

Calculated Members/Average Patient Count per Decade.pivot

All in my local Caché installation.

**Comment by eduard93** [comment]
What's your XData line in MDX2JSON.REST? 
 <Route Url="/Widgets" Method="POST" Call="GetWidgetsList" Body="Dashboard"/>

**Comment by evshvarov** [comment]
I think the source of this widget is KPI. MDX2JSON doesn't work with KPI at
current state.

2015-05-24 17:45 GMT+03:00 Eduard <notifications@github.com>:

**Comment by ZitRos** [comment]
> I think the source of this widget is KPI. MDX2JSON doesn't work with KPI at
> current state.

@evshvarov, It seem that not. The same error on Pivot Features/Conditional Formatting.pivot.



> What's your XData line in MDX2JSON.REST?

@eduard93, \<Route Url="/Widgets" Method="POST" Call="GetWidgetsList" Body="Dashboard"/>

**Comment by ZitRos** [comment]
As @eduard93 helped me, fixed with <code>##class(MDX2JSON.Installer).Update()</code> command, and each class recompilation.
