### ISSUE TITLE
Compiling routine MDX2JSON.Installer.1

### ISSUE THREAD

**Issue by farooqsaeedfs** [intersystems-ru/Cache-MDX2JSON#47]
I am getting following error while executing this command: 
do ##class(%Installer.Installer).InstallFromCommandLine("C:\InterSystems\m...\mgr\MDX2JSON\Installer.cls.xml","Namespace=UFT,SourceDir=C:\InterSystems\....\mgr\MDX2JSON")

Compiling routine MDX2JSON.Installer.1
MDX2JSON.Installer.1.INT(25) ERROR #1026: Invalid command : 'Return:('st)' : Offset:11 [zDeleteNamespace+4^MDX2JSON.Installer.1]
 TEXT:     	Return:('st) st

I tried to replace Return with Quit but than I start getting following error: MDX2JSON.Installer.1.INT(49) ERROR #1043: QUIT argument not allowed : 'C1)*/' : Offset:19 [#;+5^MDX2JSON.Installer.1]
 TEXT:  		&sql(CLOSE C1)*/

**Comment by eduard93** [comment]
What's your Caché version?

**Comment by farooqsaeedfs** [comment]
Thanks for the response Ed.

I am using 2012.2.5.962.0 version of Ensemble.

**Comment by farooqsaeedfs** [comment]
I am pasting response from $ZV as well.

%SYS>W $ZV
Cache for Windows (x86-64) 2012.2.5 (Build 962U) Wed Jul 24 2013 21:10:21 EDT

**Comment by eduard93** [comment]
Return operator is introduced in Caché 2014. Support for REST web applications is also introduced in Caché 2014. So, to use MDX2JSON you need to upgrade to Caché/Ensemble 2014 version (or later).

**Comment by ZitRos** [comment]
> Support for REST web applications is also introduced in Caché 2014

On VMonkey UAT we have 2013.2, and REST works great. I suppose the error is in syntax: <code>quit:(\<post-condition>) \<value></code>

**Comment by eduard93** [comment]
@ZitRos You have a REST client, which is essentially an HTTP requests wrappers. I'm talking about REST server support, with Caché as a server part and it was introduced in Caché 2014.

**Comment by eduard93** [comment]
<code>Return</code> operator also appeared only in 2014. It does not support arguments in some code blocks, yes.

**Comment by ZitRos** [comment]
> @ZitRos You have a REST client, which is essentially an HTTP requests wrappers. I'm talking about REST server support, with Caché as a server part and it was introduced in Caché 2014.

Got it, OK. So, maybe installing REST client will solve this, or you know better.

**Comment by eduard93** [comment]
Copying %CSP.REST won't solve this problem - there is also CSPGateway support and  webapplications "DispatchClass" property.

**Comment by farooqsaeedfs** [comment]
I was thinking to update the installer code according to Cache 2012 syntax. But seems like even if it gets installed its going to give me problem due to CSPGateway support and DispatchClass property you mentioned.

**Comment by eduard93** [comment]
Yes. You need to upgrade to use MDX2JSON, I'm afraid. I'll add this info to README.

**Comment by farooqsaeedfs** [comment]
What if I need only JSON part of it. I mean instead of REST service I can use SOAP. And somehow I already updated Utils and ResultSet files syntax I mean replacing Return with Quit.

Do you think there will be still something which I should consider or keep in mind or any functionality I am going to miss ?

Thank you so much for prompt replying always.

**Comment by eduard93** [comment]
Check MDX2JSON.REST and white SOAP wrappers similarly. I do not foresee any huge problems with that. You may have some problems with CSP macros I use, as they may be missing in 2012.2.5.962.0 so if something fails to compile it may be because of some macro. Does Utils and ResultSet compile?

Also, please fork and commit to that repository. It would be appreciated.

**Comment by farooqsaeedfs** [comment]
Yeah I have to update many macros in Utils and few in ResultSet, now both are compiling. I am currently trying to access these in my .NET code.

What is this Fork and commit ?

**Comment by eduard93** [comment]
It's related to source control system we use here called git. [Forking](https://guides.github.com/activities/forking/) is a process of contributing to someone else code (for example, MDX2JSON). [Info2](https://help.github.com/articles/fork-a-repo/). [Commit](http://media.pragprog.com/titles/tsgit/chap-005-extract.html) is a small set of changes in a project. To develop with Caché+Git+GitHub you need [cache-tort-git](https://github.com/eduard93/cache-tort-git) project.

**Comment by eduard93** [comment]
"I am currently trying to access these in my .NET code"
How's it going? SOAP is a better way, but you can write json to stream (via relevant methods in jsonProvider or [output redirection](https://code.intersystems.com/code/Code.View.Code.cls?ID=832)) and expose that as SQL procedure and call it from .NET via ODBC. Still, I do recommend SOAP. It's a cleaner solutions. Are there any problems?

**Comment by farooqsaeedfs** [comment]
I will definitely fork and commit once I make it workable. 

Right now I am trying to fix following error:

|ŠB<UNDEFINED>zProcessOneAxisCell+54^NHCP.SVC.ResultSet.1 *%request-zProcessOneAxisCell+54^NHCP.SVC.ResultSet.1Target has exited debugger

and I was wondering what is this method .%OutputJSON in ResultSet ?

**Comment by eduard93** [comment]
>Right now I am trying to fix following error:
I don't see %request variable in ProcessOneAxisCell method. It's HTTP request object (%CSP.Request class). What's the code in BzProcessOneAxisCell+54 anyway?

>and I was wondering what is this method .%OutputJSON in ResultSet ?
In MDX2JSON.ResultSet?

**Comment by farooqsaeedfs** [comment]
In MDX2JSON.ResultSet?
 Yes

I don't see %request variable in ProcessOneAxisCell method. It's HTTP request object (%CSP.Request class). What's the code in BzProcessOneAxisCell+54 anyway?

This code line is at: set key = $O($$$DeepSeeAxisGLVN(CubeIndex, AxisKey, "axes", Node, "ch", key))

**Comment by eduard93** [comment]
>%OutputJSON

It's not present in [current version](https://github.com/intersystems-ru/Cache-MDX2JSON/blob/master/MDX2JSON/ResultSet.cls.xml). It was an elaboration on %DeepSee.ResultSet:%OutputJSON method.

>The code line at 54 is: set key = $O($$$DeepSeeAxisGLVN(CubeIndex, AxisKey, "axes", Node, "ch", key))

I meant int code, not cls code, but okay.
Well, I'd check if this global path exists and same/similar to 2014.1+ DeepSee global structure. How do you debug? Have you tried reproducing this error from terminal context? I usually debug in terminal+zw+write to globals.

**Comment by farooqsaeedfs** [comment]
I just set my debug target to ClassMethod. I used to hard code my mdx query inside.

**Comment by eduard93** [comment]
Closed due to inactivity
