### ISSUE TITLE
MDX Parallel Execution

### ISSUE THREAD

**Issue by v23ent** [intersystems-ru/Cache-MDX2JSON#49]
`Class MDX2JSON.Utils`
`ClassMethod GetResultSet`

Есть достаточно большая уверенность, что используемый вызов
    `set RS = ##class(MDX2JSON.ResultSet).%ExecuteDirect(pMDX,.Params,.pStatus)`
обрабатывает запрос в один поток.

Если заменить на:
    `set RS = ##class(MDX2JSON.ResultSet).%New()`
    `set st = RS.%PrepareMDX()`
    `set st = RS.%ExecuteAsync(pMDX,.Params,1)`

То должно начать работать значительно быстрее.
Код дан в качестве примера, использования другого метода. Для реального использования, надо  его правильно встроить в контекст.

**Comment by eduard93** [comment]
Ок, посмотрю
