### ISSUE TITLE
Long output/Buffer?

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/Cache-MDX2JSON#51]
When I send dashboard request
`POST http://localhost:57772/MDX2JSON/Dashboard?Namespace=Samples`
With headers
`Content-Type: application/json`
And body
`{"Dashboard":"Widget Examples/All Charts.dashboard"}`
The output is garbage.

The problem arises in `MDX2JSON.Utils` class, `GetDashboard` method.

The problem seems to be related to the length of the output. 
Consider the following modified `GetDashboard` method:

```
ClassMethod GetDashboard(pDashName As %String) As %Status
{
	try {
		set st = ##class(MDX2JSON.DashboardFilters).OpenDashboardByName(pDashName, .dash)
		return:($$$ISERR(st)) st
		
		set st = ##class(MDX2JSON.DashboardFilters).WidgetsToProxyObject(dash, .widgetlist)
		return:($$$ISERR(st)) st
		
		//do widgetlist.displayInfo.%ToJSON()
		//do widgetlist.info.%ToJSON()
		set filters = widgetlist.filters
		set widgets = widgetlist.widgets
		
		
		#dim widgets As List of %ZEN.proxyObject
		for i=1:1:5 {
			set widget = widgets.GetAt(i)
			zw widget
		}
		//set widget = widgets.GetAt(5)
		//zw widget
	} catch ex {
		do ex.Log()
	}
	return st
}
```

After I tested this method (by changing  the total number of cycles in `for i=1:1:5`), I found out, that:
  - loop size = 5 (as in code)  output is garbage
  -  loop size = 4  output is wrong, but readable
  - loop size = 3  output is correct

Also, it doesn't matter from where to start. So, for example `for i=4:1:5` executes ok, but `for i=6:1:11` output is wrong.

`Cache for Windows (x86-64) 2016.1 (Build 656U) Fri Mar 11 2016 17:42:42 EST`

@dmitry-zasypkin

**Comment by eduard93** [comment]
Please reproduce.

**Comment by eduard93** [comment]
Tinkered with GZIP settings for app (in CSP Gateway management), now I receive wrong, but readable reply from server.

**Comment by eduard93** [comment]
Bug does not appear on 15.1
Bug appears on 16.1 with new dynamic objects and old dynamic objects.

**Comment by eduard93** [comment]
Here's an intresting thing:
1. Enable new dynamic objects `set ^MDX2JSON("Features")="newjson"`
2. Compile MDX2JSON package
3. Replace json macro in `GetDashboard` method with:
```
set str = ##class(%Stream.GlobalCharacter).%New()

do widgetlist.$toJSON(.str)

set ^a = ""
while 'str.AtEnd {
	set ^a = ^a _ str.Read()
}
write ^a
```

The output is wrong (readable, but not full), but ^a global contains correct json

**Comment by eduard93** [comment]
When I compare ^a with HTTP output, turns out that HTTP output is just ^a but with the first 4096 characters skipped, only last 3531 characters are written.

**Comment by eduard93** [comment]
@zitros any ideas?

**Comment by ZitRos** [comment]
@eduard93, new 2016.1 JSON capabilities have some strange bugs that likely to be fixed.

[Here](https://github.com/intersystems-ru/cache-visual-editor/commit/804627789e092676f4c1f2132b3276494fb827cd) is the fix that does work for me. Try if it works for you as well.

**Comment by eduard93** [comment]
@ZitRos already use [that](https://github.com/intersystems-ru/Cache-MDX2JSON/commit/3081e4e7b1a3d81c364728a21002bdd8daca098c) circa 15.3

**Comment by ZitRos** [comment]
@eduard93, why didn't you place `w ""` inside `DynObjToJSON` macro? Could you please refer me to the code of this macro?

**Comment by eduard93** [comment]
[It expands](https://github.com/intersystems-ru/Cache-MDX2JSON/blob/master/MDX2JSON/MDX2JSON.inc.xml#L37) into `do widgetlist.%ToJSON()` where widgetlist is a `%ZEN.proxyObject` (or `%Object` if a flag to use new dynamic objects is set)

**Comment by ZitRos** [comment]
Just a thing to try, does the next works properly:
```pascal
set str = ##class(%Stream.GlobalCharacter).%New()
do widgetlist.$toJSON(.str)
do str.OutputToDevice()
```

**Comment by eduard93** [comment]
No, still skips first 4096 symbols

**Comment by ZitRos** [comment]
And does this?
```pascal
set str = ##class(%Stream.GlobalCharacter).%New()
do widgetlist.$toJSON(.str)
while 'str.AtEnd {
  write str.Read()
}
```

**Comment by eduard93** [comment]
This skips first 4096 symbols too.

**Comment by ZitRos** [comment]
So I don't have ideas anymore. I recommend you to debug the stream (for example, output N first characters and compare them to the global) and decide whether this is a $toJSON issue or a stream issue. Check if stream position is set to 0.

**Comment by evshvarov** [comment]
Raise question on DC?

суббота, 21 мая 2016 г. пользователь Nikita написал:

**Comment by eduard93** [comment]
@evshvarov if no answer would be found till Monday, I'll start writing minimal test case, independent of mdx2json. After that, sure.

**Comment by eduard93** [comment]
Turns Out, it was IO redirect issue

**Comment by ZitRos** [comment]
So how did you fix this issue?

**Comment by eduard93** [comment]
Currently: removed unrequited IO redirects.
TODO: modify my redirect code, so it won't cause an error

**Comment by eduard93** [comment]
The discussion continues at [InterSystems Developer Community](https://community.intersystems.com/post/rest-and-io-redirection).
