### ISSUE TITLE
Portlet registration service for DSW

### ISSUE THREAD

**Issue by gnibeda** [intersystems-ru/Cache-MDX2JSON#58]
**Description** 

We need more simple and clear addons installation for DSW. At present, to install addon, user need two files `*.js` with client-side widget code and `*.xml` with custom portlet. It is not convenient to supply two different files as one addon, so I suggest to create service which can automatically create portlet classes for DSW addons. As a result, only one file would be needed to install DSW addon.

**Requirements**

REST service should receive array of portlet names to create. Portlets are to be created only in case of absence.
Input example: ["DSW.CusmtomMap", "DSW.TestWidget"]

This service would be called on DSW startup with all addons names as input.

**Comment by eduard93** [comment]
DSW passes array of `WidgetName` and MDX2JSON checks classes `DSW.Addons.WindgetName` annd creates if required:

```
Class DSW.CustomPortlet Extends %DeepSee.Component.Portlet.abstractPortlet
{
}
```

**Comment by eduard93** [comment]
is DSW Package mapped?

**Comment by eduard93** [comment]
`POST /Addons` 
`[ "Addon1", "Addon2", ..., "AddonN"]`  body
