### ISSUE TITLE
List of files in folder for DSW

### ISSUE THREAD

**Issue by gnibeda** [intersystems-ru/Cache-MDX2JSON#59]
To support custom themes feature of DSW we need to be able to receive list of files in `themes` folder.
REST service should receive folder name as input and return list of files contained in this folder.

Input example: "/css/themes"
Response: ["theme1.css", "theme2.css", "theme3.css"]

**Comment by eduard93** [comment]
Let's fix the dir same as with addons

**Comment by eduard93** [comment]
Call GET /Themes. 
Path fised to dsw/themes
