### ISSUE TITLE
Needs standalone installation file

### ISSUE THREAD

**Issue by daimor** [intersystems-ru/Cache-MDX2JSON#60]
By security reasons my server doesn't have an access to github. So, I need a standalone installer.

**Comment by eduard93** [comment]
https://github.com/intersystems-ru/Cache-MDX2JSON#offline-installation

**Comment by daimor** [comment]
It needs direct access to the server, which I don't have. Only access to Caché

**Comment by eduard93** [comment]
If you have MDX2JSON installed, just import new files into studio.

**Comment by eduard93** [comment]
I'll add installer flag to skip file/github load though.
