### ISSUE TITLE
For Some Reason MDX2JSON Sends COUNT total while it should be empty

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/Cache-MDX2JSON#61]
Came from [this issue](https://github.com/intersystems-ru/LightPivotTable/issues/4).
![2017-02-13_145156](https://cloud.githubusercontent.com/assets/4989256/22884320/08a2fd20-f1fd-11e6-8a4b-c149a4471d21.png)
DeepSee ZEN doesn't have any `COUNT` total applied. Instead, in *.pivot, there is a `SUM` total. So the total value sent by MDX2JSON forces LPT to reassign total for this column.

**Comment by eduard93** [comment]
link to testcase please?

**Comment by ZitRos** [comment]
See the related issue I have linked above.

**Comment by eduard93** [comment]
Results reported by MDX2JSON are accurate:
![default](https://cloud.githubusercontent.com/assets/5127457/22892685/7d7ec094-f224-11e6-8cc9-8ccf41a50b2c.PNG)

See [pivot](http://146.185.143.59/csp/samples/_DeepSee.UserPortal.Analyzer.zen?PIVOT=test%2FLPT4.pivot)

**Comment by eduard93** [comment]
Both COUNT aggregate and SUM aggregate result in 1000. And also empty aggregate, which defaults to COUNT

**Comment by eduard93** [comment]
[Docs](http://docs.intersystems.com/latest/csp/docbook/DocBook.UI.Page.cls?KEY=D2MODEL_ch_meas#D2MODEL_meas_aggregation)

**Comment by evshvarov** [comment]
Interesting. BTW, if I decide to count the number of rows, what should I
do?

**Comment by eduard93** [comment]
@evshvarov it is a perfect question for InterSystems Community!

**Comment by ZitRos** [comment]
Pardon. When I was checking this in DSZ, the aggregate was empty... OK,
I'll check this on LPT side.

**Comment by ZitRos** [comment]
Yes, I was assuming that COUNT counts the number of rows, at least this is
the way how it is coded in LPT.
