### ISSUE TITLE
DeepSeeWeb, WriteAddons error

### ISSUE THREAD

**Issue by daimor** [intersystems-ru/Cache-MDX2JSON#62]
User only with only one resource to concrete database
`{"Error":"ERROR #5002: Cache error: <PROTECT>zWriteAddons+3^MDX2JSON.REST.1 *c:\\intersystems\\ensemble\\mgr\\"}`

I'm not going to use any addons. 
Why is it trying to write something to CACHESYS Database?

**Comment by eduard93** [comment]
Please provide  `http://host:port/MDX2JSON/Test?Debug`
