### ISSUE TITLE
Allow to return more than 1000 rows for the listing

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/Cache-MDX2JSON#64]
Now there is a limit of 1000

**Comment by eduard93** [comment]
http://do.intersystems.ru/issues/1216

**Comment by eduard93** [comment]
`DRILLTHROUGH MAXROWS 20000 SELECT FROM [HoleFoodsBudget]`

**Comment by evshvarov** [comment]
Why only 20000?

**Comment by eduard93** [comment]
@evshvarov just an example
