### ISSUE TITLE
It seems that every filter request in a widget loads all the member for all the filters in a widget

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/Cache-MDX2JSON#65]

**Comment by eduard93** [comment]
Докуинуть в запрос список фильтров для которых нужно получить значения
И сооветственно возвращать только их
Сделал на dsw так
в запрос /Filters добавил свойство RelatedFilters
это массив путей фильтров которые нужны
"[ComputedD].[H1].[Computed]"
можем по названиям фильтровать

**Comment by gnibeda** [comment]
fixed in 2.1.1:
https://github.com/intersystems-ru/DeepSeeWeb/releases/tag/2.1.1

**Comment by eduard93** [comment]
Any speed improvements due to this//
