### ISSUE TITLE
Error #5844 and #6315 

### ISSUE THREAD

**Issue by annietongisc** [intersystems-ru/Cache-MDX2JSON#73]
DEMO>Do ##class(MDX2JSON.Installer).setup() 
2021-06-29 13:58:10 0 MDX2JSON.Installer: Installation starting at 2021-06-29 13:58:10, LogLevel=0
2021-06-29 13:58:10 0 : Set namespace to MDX2JSON
2021-06-29 13:58:10 0 : Set Import to 1
2021-06-29 13:58:11 0 : SourceDir undefined - online install from GitHub

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/YlJwTZX2hPabYg.xml as xml
Imported class: MDX2JSON.AbstractREST
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/e4tFUskgv1bG0A.xml as xml
Imported class: MDX2JSON.Dashboard
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/9EnWHaZRUFoFeg.xml as xml
Imported class: MDX2JSON.DashboardFilters
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/Hdfkrwv9c0HLOg.xml as xml
Imported class: MDX2JSON.DashboardRS
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/bYWWr0m8nhhmbg.xml as xml
Imported class: MDX2JSON.EmptyPortlet
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/b6nhS91csCVttA.xml as xml
Imported class: MDX2JSON.Installer
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/LWiSU50ZbTamPQ.xml as xml
Imported routine: MDX2JSON.MDX2JSON.INC
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/YVeqw7caVN97YA.xml as xml
Imported class: MDX2JSON.REST
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/CkqEXZ7lNbiH4g.xml as xml
Imported class: MDX2JSON.ResultSet
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/Z2IdGoFjmPQlsQ.xml as xml
Imported class: MDX2JSON.Tests
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/bu6bwDvP9Cm07g.xml as xml
Imported class: MDX2JSON.Users
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/ugRHKW7AP5es5A.xml as xml
Imported class: MDX2JSON.Utils
Load finished successfully.

Load started on 06/29/2021 13:58:11
Loading file /opt/asiris/mgr/Temp/Y5qVahAjnkBOOA.xml as xml
ERROR #5844: User defined document 'MDX2JSON.ZPM' not supported. No user defined document class in this namespace.
  > ERROR #6315: Errors reporting importing XML subelement in file '/opt/asiris/mgr/Temp/Y5qVahAjnkBOOA.xml' at line '3' offset '31', skipping this item.
Detected 1 errors during load.

Compilation started on 06/29/2021 13:58:11
Compiling 11 classes
Compiling class MDX2JSON.Dashboard
Compiling class MDX2JSON.AbstractREST
Compiling class MDX2JSON.DashboardRS
Compiling class MDX2JSON.Installer
Compiling class MDX2JSON.ResultSet
Compiling class MDX2JSON.Tests
Compiling class MDX2JSON.Users
Compiling class MDX2JSON.Utils
Compiling class MDX2JSON.EmptyPortlet
Compiling class MDX2JSON.DashboardFilters
Compiling class MDX2JSON.REST
Compiling routine MDX2JSON.AbstractREST.1
Compiling routine MDX2JSON.Dashboard.1
Compiling routine MDX2JSON.EmptyPortlet.1
Compiling routine MDX2JSON.DashboardRS.1
Compiling routine MDX2JSON.ResultSet.1
Compiling routine MDX2JSON.Installer.1
Compiling routine MDX2JSON.Tests.1
Compiling routine MDX2JSON.Users.1
Compiling routine MDX2JSON.Utils.1
Compiling routine MDX2JSON.DashboardFilters.1
Compiling routine MDX2JSON.REST.1
Generating file: /opt/asiris/csp/broker/MDX2JSON.js
Compilation finished successfully in 2.936s.
2021-06-29 13:58:14 0 MDX2JSON.Installer: ERROR #5844: User defined document 'MDX2JSON.ZPM' not supported. No user defined document class in this namespace.
  > ERROR #6315: Errors reporting importing XML subelement in file '/opt/asiris/mgr/Temp/Y5qVahAjnkBOOA.xml' at line '3' offset '31', skipping this item.
2021-06-29 13:58:14 0 MDX2JSON.Installer: Installation failed at 2021-06-29 13:58:14
2021-06-29 13:58:14 0 %Installer: Elapsed time 3.853703s

**Comment by eduard93** [comment]
No zpm installed, fix is to load stuff from `MDX2JSON` folder.
