### ISSUE TITLE
MDX2JSON is very slow on some crossjoin queries 

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/Cache-MDX2JSON#74]
An example is in ZPM analytics

**Comment by eduard93** [comment]
We agreed that it's not a MDX2JSON issue yesterday? Countries monthly MDX is executed for below 200ms.
![image](https://user-images.githubusercontent.com/5127457/127296872-c66a45dc-efa3-4be0-ab68-7a41bb0275e7.png)

Or is there something else?

**Comment by evshvarov** [comment]
Yes, we can close it
